version: '3'

services:
  app:
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=admin
    image: emqx/emqx:5.0.10
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - "1883:1883"
      - "8083:1883"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    restart: unless-stopped
    volumes:
      - data:/opt/emqx/data
      - log:/opt/emqx/log

volumes:
  data:
  log:
